//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCounter
    {
        public int AssetCounterID { get; set; }
        public int AssetType { get; set; }
        public int AssetSubType { get; set; }
        public int Count { get; set; }
        public string ClientIdentifier { get; set; }
    }
}
